"""
core/adaptive.py

The adaptive integrator: advances the system one `dt` at a time with the
cheap custom Leapfrog (Velocity Verlet) by default, and hands the state over
to IAS15 (REBOUND) whenever the safety score says Leapfrog is no longer
trustworthy. Unlike core.leapfrog.run_leapfrog_with_correction, it NEVER
looks at the IAS15 reference trajectory -- it has to decide from its own
state alone, which is the whole point of the safety index.

Per step:

    1. Decide which integrator takes this step, from the safety score of the
       CURRENT state (computed at the end of the previous step):
           in Leapfrog:  switch to IAS15 if score >= safety_threshold
           in IAS15:     stay in IAS15 while score >= release_fraction *
                         safety_threshold, otherwise return to Leapfrog
       (release_fraction < 1 adds hysteresis so the method does not flip
       integrators every step when the score hovers around the threshold;
       1.0 means no hysteresis.) The very first step has no jerk history,
       so it is always taken by Leapfrog.
    2. Advance one dt with that integrator.
    3. Recompute the accelerations, the safety features and the score for
       the new state (features are defined exactly as in the calibration
       data: see core/safety_index.py).

State is transferred between the two integrators through plain positions /
velocities, in both directions. Both use the same frame, G and softening.
A fresh REBOUND simulation is built at each Leapfrog -> IAS15 switch (so
IAS15's adaptive step-size guess restarts there); consecutive IAS15 steps
reuse the same simulation.

Rewinding (optional, rewind=True): detection is often LATE -- by the time the
score crosses the threshold, Leapfrog has already drifted. With rewinding on,
the integrator keeps the last `checkpoint_count` checkpoints (full state +
bookkeeping, in RAM), one every `checkpoint_interval` steps. When the score
reaches the threshold while in Leapfrog, it does NOT switch at the current
state: it restores the checkpoint `rewind_back` places before the latest one
(default 1 = the SECOND-LATEST; the oldest one if fewer exist) and replays from
there with IAS15. Details:

    * IAS15 is forced from the checkpoint up to and including the step at which
      the trigger fired, so every rewind makes net progress (no rewind loops).
      After that the normal release rule applies.
    * Release: IAS15 is kept until the score is below release_fraction *
      safety_threshold, then for `ias15_hold_steps` further steps.
      (ias15_hold_steps also works without rewinding; 0 = release at once.)
    * Everything recorded after the checkpoint (samples, switch events,
      counters, correction count, the stateful index's memory) is discarded and
      regenerated by the replay, so the returned Trajectory / AdaptiveLog
      describe only the final, rewound timeline.

False-positive detection (optional, detect_false_positives=True): a trigger is a
FALSE POSITIVE if IAS15 was not needed, i.e. Leapfrog would have stayed close to
IAS15 the whole time. Detected causally (no reference trajectory): from the
moment an IAS15 stretch starts, a SHADOW Leapfrog is advanced in lockstep from the
same starting state (for a rewind: from the restored checkpoint, so it reproduces
the discarded Leapfrog timeline). Each step, the RMS position difference between
shadow and actual state is tracked. When the stretch ends, if the largest
difference stayed below false_positive_threshold, the stretch is a false positive
(same RMS metric as the correction / error threshold). Detection only: it does not
change what the integrator does. One IAS15Stretch record per stretch is returned in
AdaptiveLog.stretches. Limitation: the verdict only sees the stretch's own
duration (trigger to release, incl. the hold steps); drift that would only have
exceeded the threshold later is not counted against the trigger.

Rollback-depth analysis (optional, analyze_rollback=True; needs rewind=True and an
IAS15 `oracle` trajectory, so it is a validation tool -- the algorithm itself
never sees the oracle): measures how many errors a DEEPER rollback could have
prevented. At every rewind, each checkpoint still in the queue is used as a
counterfactual restore point: IAS15 is replayed from it to the trigger step and
the result is compared with the exact IAS15 state at that step (the oracle,
advanced from its nearest sample). A candidate is EFFECTIVE if its deviation is
at most max(rollback_clean_threshold, (1 - rollback_min_gain) * the deviation of
the un-rewound state), i.e. the rewind removes at least `rollback_min_gain` of the
error (or lands on an essentially exact state). An absolute 'clean' test is not
usable: Leapfrog is never bit-exact, so every queued checkpoint after t=0 would
fail it. Each rewind is then classed:

    adequate         the checkpoint actually used was effective;
    improvable       it was not, but a deeper checkpoint IN THE QUEUE was (a larger
                     rewind_back would have removed more of the error);
    drift_dominated  no queued checkpoint was: the error was accumulated long before
                     the queue's window (slow Leapfrog drift), so no rollback depth
                     inside it can fix it.

Every later error (RMS position error vs the oracle above rollback_error_threshold
at a sample) is attributed to the rewinds since the last clean point (the start,
the last snap back to the reference when correcting, or the last resync):
'improvable' if any of those rewinds was improvable, else 'accumulated_drift' if
any was drift_dominated, else 'after_adequate_rewinds' (rewinds were effective:
chaos / IAS15 divergence / drift after release), else 'undetected' (no rewind at
all: the score never fired).
'improvable' errors are the ones a deeper rollback could have prevented. This is
an attribution, not a proof: it links an error to an insufficient rewind, it does
not re-run the whole simulation with the deeper rollback.

Drift budget (optional, drift_budget > 0): the dominant error of a Leapfrog run is
SLOW accumulated phase drift over thousands of calm steps, which neither the
safety score (it only sees close approaches) nor a short rewind can see or undo.
While in Leapfrog, a shadow Leapfrog with half the step (dt/2) is advanced in
lockstep from the same state. Velocity Verlet is second order, so the coarse
run's accumulated error is ~ (4/3) * RMS|x(dt) - x(dt/2)|. When that estimate
reaches drift_budget * drift_error_threshold, the state is RESYNCED to the
Richardson extrapolation (4 * x_fine - x_coarse) / 3 (same for velocities), which
removes the leading error term, and the shadow restarts from it. Cost ~3 force
evaluations per Leapfrog step instead of 1. Needs no reference. Caveat: the
extrapolation assumes smooth dynamics; close encounters are the safety score's job.

Resync on switch (optional, resync_on_switch=True): the drift budget above only sees
error accumulated INSIDE the current Leapfrog stretch, and an IAS15 handoff freezes
that error into the state (IAS15 only stops it growing), so in practice budget
resyncs almost never fire while every stretch still hands over a contaminated
state. With this option the Richardson extrapolation is applied to the state that
IAS15 takes over from: at every rewind the restored checkpoint is repaired with the
dt/2 shadow saved in it (and at a plain switch the current state is). Each Leapfrog
stretch then ends with a repair, so error cannot pile up from stretch to stretch,
and no long rollback is needed. Implies the dt/2 shadow runs (same cost as the
drift budget); the repaired state also becomes the anchor.

Anchor rewinding (optional, rewind_to_anchor=True): instead of the checkpoint
`rewind_back` places before the latest one, rewind to the ANCHOR, the last state
that was verified: the start, the last resync, the last snap back to the reference
(validation), or the end of an IAS15 stretch that itself started from the anchor.
The replay is IAS15 from there to the trigger step, so it repairs accumulated
drift at the price of a long IAS15 stretch (up to the distance between anchors).
Combine with drift_budget to keep that distance bounded.

Compensated sums (optional, compensated_sums=True): at ~1e-16 per step, double-precision
roundoff in `x += v*dt + ...` and `v += ...` accumulates over the ~200k Leapfrog steps of a run
and becomes the seed that chaos (Lyapunov time ~3) amplifies into a threshold error, long after
the truncation error has been removed by the Richardson repairs. With this option the position
and velocity sums are Kahan-compensated in the main Leapfrog step AND in the shadow runs, the
compensation terms are checkpointed / restored with the state, and the Richardson repair is
written as `base + small correction` with the rounding of that last add kept in the compensation
(so a resync no longer injects ~1e-16 of fresh roundoff). Compensation is reset to zero when the
state comes from REBOUND or from the reference (both are taken as exact). Off (default) the
integration is bit-identical to the version without this option.

Richardson levels (optional, richardson_levels=3): also runs a dt/4 shadow and repairs with the
6th-order combination (64 x_quarter - 20 x_half + x_coarse) / 45 instead of (4 x_half - x_coarse)/3.
Velocity Verlet is symmetric (error series in even powers of dt), so this removes the h^4 term too.
Costs ~7 instead of ~3 force evaluations per Leapfrog step. Without compensated_sums the
extra order is mostly wasted, because roundoff, not truncation, is then the floor.

Note: switching to IAS15 does not repair error Leapfrog has ALREADY
accumulated -- it only stops further accumulation. That is inherent to the
method (there is no reference to snap back to) and is exactly what the
validation experiment measures.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field, replace
from typing import Callable

import numpy as np
import rebound

from core.jit_kernels import HAVE_NUMBA
from core.leapfrog import Trajectory
from core.metrics import position_error
from core.physics import System, compute_accelerations
from core.safety_index import (
    IndexScale,
    SafetyFeatures,
    compute_safety_features,
    system_safety_score,
)

if HAVE_NUMBA:
    from core.jit_kernels import vv_step_kernel


@dataclass
class SwitchEvent:
    """
    One change of integrator.

    Attributes:
        step: 1-indexed step at which the NEW integrator took its first step.
        time: Simulated time at the start of that step.
        to_integrator: "ias15" or "leapfrog".
        score: The 0-1 safety score that triggered the switch.
    """

    step: int
    time: float
    to_integrator: str
    score: float


@dataclass
class RewindEvent:
    """
    One rewind.

    Attributes:
        step: The step that was about to be taken when the score crossed the threshold.
        to_step: Step count of the checkpoint restored (state at the END of that step).
        time: Simulated time at the detection.
        to_time: Simulated time of the restored checkpoint.
        score: The 0-1 safety score that triggered the rewind.
        depth: Which checkpoint was restored, counted back from the latest (0 = latest;
            -1 = the anchor, with rewind_to_anchor).
        analysis: Rollback-depth counterfactuals (None unless analyze_rollback was on).
    """

    step: int
    to_step: int
    time: float
    to_time: float
    score: float
    depth: int = 1
    analysis: "RollbackAnalysis | None" = None


@dataclass
class RollbackAnalysis:
    """
    Counterfactual check of every checkpoint available at one rewind.

    Attributes:
        dev_leapfrog: RMS position error, vs the oracle, of the state at the trigger
            (i.e. what plain switching without rewinding would have kept).
        dev_by_depth: dev_by_depth[d] = RMS position error, vs the oracle at the trigger
            step, of IAS15 replayed from the checkpoint d places before the latest.
        steps_by_depth: Step count of each of those checkpoints.
        chosen_depth: Depth actually used (RewindEvent.depth).
        category: 'adequate' | 'improvable' | 'drift_dominated' (see module docstring).
        best_depth: Depth with the smallest deviation.
        min_adequate_depth: Shallowest depth deeper than the chosen one whose deviation
            is effective; -1 if none (or the chosen one was already effective).
        dev_anchor: Same counterfactual for the ANCHOR (IAS15 replayed from the last
            verified state); None if the anchor was further than the analysis replay cap.
        anchor_step: Step count of that anchor.
    """

    dev_leapfrog: float
    dev_by_depth: list[float]
    steps_by_depth: list[int]
    chosen_depth: int
    category: str
    best_depth: int
    min_adequate_depth: int
    dev_anchor: float | None = None
    anchor_step: int | None = None


@dataclass
class RollbackError:
    """
    One error sample (RMS position error vs the oracle above the threshold) and its cause.

    Attributes:
        step: Step at which the error was observed.
        time: Simulated time.
        error: RMS position error at that sample (before any correction).
        category: 'improvable' (a deeper rollback could have prevented it),
            'accumulated_drift' (no queued checkpoint could have; the error is slow
            Leapfrog drift), 'after_adequate_rewinds' or 'undetected'.
    """

    step: int
    time: float
    error: float
    category: str


@dataclass
class ResyncEvent:
    """
    One drift-budget resync (state replaced by the Richardson extrapolation).

    Attributes:
        step: Step at whose end the resync happened.
        time: Simulated time.
        estimated_error: Estimated accumulated RMS position error just before the resync.
        dev_before: True RMS position error vs the oracle before the resync
            (None unless analyze_rollback was on).
        dev_after: True RMS position error vs the oracle after the resync (same).
        kind: 'budget' (mid-stretch, drift budget reached) or 'switch' (repair applied
            to the state IAS15 takes over from).
    """

    step: int
    time: float
    estimated_error: float
    dev_before: float | None = None
    dev_after: float | None = None
    kind: str = "budget"


@dataclass
class IAS15Stretch:
    """
    One contiguous run of IAS15 steps (trigger -> release), with the false-positive verdict.

    Attributes:
        start_step: First step IAS15 took (for a rewind: checkpoint step + 1).
        start_time: Simulated time at the start of that step.
        end_step: Last step IAS15 took (inclusive).
        n_steps: Number of IAS15 steps in the stretch.
        trigger_score: Safety score that triggered the stretch.
        peak_score: Largest safety score seen during the stretch.
        max_deviation: Largest RMS position difference between the shadow Leapfrog
            and the actual state during the stretch.
        false_positive: max_deviation < false_positive_threshold.
        rewound: True if the stretch was started by a rewind.
        complete: False if the run ended while still in this stretch.
    """

    start_step: int
    start_time: float
    end_step: int
    n_steps: int
    trigger_score: float
    peak_score: float
    max_deviation: float
    false_positive: bool
    rewound: bool
    complete: bool = True


@dataclass
class _ActiveStretch:
    """Live bookkeeping (and the shadow Leapfrog state) of the IAS15 stretch in progress."""

    start_step: int
    start_time: float
    trigger_score: float
    rewound: bool
    sh_pos: np.ndarray
    sh_vel: np.ndarray
    sh_acc: np.ndarray
    n_steps: int = 0
    peak_score: float = 0.0
    max_dev: float = 0.0

    def copy(self) -> "_ActiveStretch":
        return replace(self, sh_pos=self.sh_pos.copy(), sh_vel=self.sh_vel.copy(), sh_acc=self.sh_acc.copy())


@dataclass
class _Checkpoint:
    """Everything needed to resume the run from the end of step `step`."""

    step: int
    positions: np.ndarray
    velocities: np.ndarray
    acc: np.ndarray
    acc_prev: np.ndarray | None
    score: float
    raw_now: float
    n_switches: int
    n_events: int
    n_ias15_steps: int
    ias15_steps_this_interval: int
    n_corrections: int
    n_samples: int  # length of every per-sample output list at this point
    index_state: object | None  # stateful raw-index memory (SituationIndex), else None
    stretch: _ActiveStretch | None  # IAS15 stretch in progress at this point (with its shadow)
    n_stretches: int  # number of finished stretch records at this point
    n_rollback_errors: int  # number of rollback-error records at this point
    taint: tuple  # (improvable, drift_dominated, adequate) rewind flags since the last clean point
    n_resyncs: int  # number of resync records at this point
    drift: tuple | None  # shadow level states at this point; None while in IAS15
    cx: np.ndarray | None = None  # Kahan compensation of positions / velocities at this point
    cv: np.ndarray | None = None


@dataclass
class AdaptiveLog:
    """
    Per-sample record of what the adaptive integrator did. All arrays are
    aligned with the returned Trajectory's `times` (length T, index 0 = t=0).

    Attributes:
        active_integrator: shape-(T,) object array; the integrator that took
            the LAST step ending at each sample ("leapfrog" or "ias15").
            Sample 0 is "leapfrog" by convention (no step taken yet).
        ias15_step_fraction: shape-(T,) fraction of the steps since the
            previous sample that were taken by IAS15 (0.0 at sample 0).
        raw_index: shape-(T,) worst-body raw safety index at each sample's
            state (NaN at sample 0, where jerk is undefined).
        safety_score: shape-(T,) 0-1 system safety score at each sample's
            state (NaN at sample 0).
        n_switches: shape-(T,) cumulative number of integrator switches.
        switch_events: Every switch, in order.
        n_steps: Total integrator steps taken.
        n_ias15_steps: How many of them IAS15 took.
        n_corrections: Number of times the state was snapped back to the IAS15
            reference (0 unless correction was enabled).
        rewind_events: Every rewind, in order (empty unless rewinding was enabled).
        n_rewinds: Number of rewinds.
        n_rewound_steps: Total steps that were discarded and replayed because of
            rewinds (extra work on top of n_steps).
        stretches: One IAS15Stretch per IAS15 stretch, in order (empty unless
            false-positive detection was enabled).
        fp_detection: Whether false-positive detection was on.
        fp_threshold: The false_positive_threshold used (None if detection was off).
        rollback_errors: One RollbackError per error sample with its attributed cause
            (empty unless analyze_rollback was on).
        rollback_analysis: Whether rollback-depth analysis was on.
        resync_events: Every drift-budget resync (empty unless drift_budget > 0).
        n_resyncs: Number of resyncs.
        drift_budget: The drift_budget used (0 = off).
    """

    active_integrator: np.ndarray
    ias15_step_fraction: np.ndarray
    raw_index: np.ndarray
    safety_score: np.ndarray
    n_switches: np.ndarray
    switch_events: list[SwitchEvent]
    n_steps: int
    n_ias15_steps: int
    n_corrections: int = 0
    rewind_events: list[RewindEvent] = field(default_factory=list)
    n_rewinds: int = 0
    n_rewound_steps: int = 0
    stretches: list[IAS15Stretch] = field(default_factory=list)
    fp_detection: bool = False
    fp_threshold: float | None = None
    rollback_errors: list[RollbackError] = field(default_factory=list)
    rollback_analysis: bool = False
    resync_events: list[ResyncEvent] = field(default_factory=list)
    n_resyncs: int = 0
    drift_budget: float = 0.0
    resync_on_switch: bool = False


def _make_ias15_sim(
    positions: np.ndarray,
    velocities: np.ndarray,
    masses: np.ndarray,
    g: float,
    softening: float,
    t: float,
) -> rebound.Simulation:
    """Build a REBOUND IAS15 simulation holding exactly the given state at time t."""
    sim = rebound.Simulation()
    sim.integrator = "ias15"
    sim.G = g
    sim.softening = softening
    for m, x, v in zip(masses, positions, velocities):
        sim.add(
            m=float(m),
            x=float(x[0]),
            y=float(x[1]),
            z=float(x[2]),
            vx=float(v[0]),
            vy=float(v[1]),
            vz=float(v[2]),
        )
    sim.t = t
    return sim


def _read_state(sim: rebound.Simulation, n: int) -> tuple[np.ndarray, np.ndarray]:
    """Copy positions/velocities out of a REBOUND simulation as (N,3) arrays."""
    positions = np.empty((n, 3), dtype=np.float64)
    velocities = np.empty((n, 3), dtype=np.float64)
    for i, p in enumerate(sim.particles):
        positions[i] = (p.x, p.y, p.z)
        velocities[i] = (p.vx, p.vy, p.vz)
    return positions, velocities


def _ias15_replay(
    positions: np.ndarray,
    velocities: np.ndarray,
    masses: np.ndarray,
    g: float,
    softening: float,
    start_step: int,
    dt: float,
    n_steps: int,
) -> np.ndarray:
    """
    Positions after `n_steps` IAS15 steps of length dt, starting from the given
    state at step `start_step`. Uses exactly the stepping of the main loop
    (a fresh sim, integrate to each multiple of dt with exact_finish_time).
    """
    if n_steps <= 0:
        return positions.copy()
    sim = _make_ias15_sim(positions, velocities, masses, g, softening, start_step * dt)
    for k in range(1, n_steps + 1):
        sim.integrate((start_step + k) * dt, exact_finish_time=1)
    return _read_state(sim, len(masses))[0]


_ANCHOR_REPLAY_CAP = 20000  # analysis only: longest anchor -> trigger replay it will simulate (steps)


def _fine_leapfrog(
    state: tuple[np.ndarray, np.ndarray, np.ndarray],
    masses: np.ndarray,
    g: float,
    softening: float,
    dt: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Advance a (positions, velocities, accelerations) state by ONE step of length dt,
    taken as TWO velocity-Verlet half-steps (the dt/2 shadow used by the drift budget)."""
    pos, vel, acc = state
    h = 0.5 * dt
    for _ in range(2):
        pos = pos + vel * h + 0.5 * acc * h * h
        new_acc = compute_accelerations(pos, masses, g=g, softening=softening)
        vel = vel + 0.5 * (acc + new_acc) * h
        acc = new_acc
    return pos, vel, acc


def _kahan_add(x: np.ndarray, c: np.ndarray, inc: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Compensated (Kahan) x += inc. The carried value is x - c; c holds what rounding dropped so far."""
    y = inc - c
    t = x + y
    return t, (t - x) - y


def _vv_step(state, masses, g, softening, h, comp):
    """One velocity-Verlet step of length h on a (pos, vel, acc, cp, cv) state.
    comp=False reproduces the plain update bit for bit; comp=True carries the rounding error of the
    position and velocity sums (cp, cv) forward instead of throwing it away."""
    pos, vel, acc, cp, cv = state
    if HAVE_NUMBA:  # compiled, identical arithmetic (incl. the Kahan updates)
        return vv_step_kernel(pos, vel, acc, cp, cv, masses, float(g), float(softening) * float(softening), float(h), bool(comp))
    if comp:
        pos, cp = _kahan_add(pos, cp, vel * h + 0.5 * acc * h * h)
    else:
        pos = pos + vel * h + 0.5 * acc * h * h
    new_acc = compute_accelerations(pos, masses, g=g, softening=softening)
    if comp:
        vel, cv = _kahan_add(vel, cv, 0.5 * (acc + new_acc) * h)
    else:
        vel = vel + 0.5 * (acc + new_acc) * h
    return pos, vel, new_acc, cp, cv


def _new_shadow(pos, vel, acc, cp, cv, levels):
    """Fresh shadow(s) from this state: the dt/2 run (levels >= 2) and, for levels == 3, the dt/4 run."""
    def one():
        return (pos.copy(), vel.copy(), acc.copy(), cp.copy(), cv.copy())
    return (one(),) if levels < 3 else (one(), one())


def _advance_shadow(dsh, masses, g, softening, dt, levels, comp):
    """Advance the shadow(s) over ONE coarse step: dt/2 run in 2 substeps, dt/4 run in 4."""
    fine = dsh[0]
    for _ in range(2):
        fine = _vv_step(fine, masses, g, softening, 0.5 * dt, comp)
    if levels < 3:
        return (fine,)
    quarter = dsh[1]
    for _ in range(4):
        quarter = _vv_step(quarter, masses, g, softening, 0.25 * dt, comp)
    return (fine, quarter)


def _repair_one(x, cx, f, cf, q, cq, levels):
    """Richardson-extrapolated (value, compensation) for one array. Written as base + small
    correction so the correction is not swamped by rounding of the O(1) values, and the rounding
    of the final add is kept in the compensation term rather than lost."""
    d_fc = (f - x) - (cf - cx)  # fine - coarse, from the compensated values
    if levels < 3:
        base, cb, corr = f, cf, d_fc / 3.0  # (4f - c)/3 = f + (f - c)/3
    else:
        d_qf = (q - f) - (cq - cf)  # quarter - fine
        base, cb, corr = q, cq, (19.0 * d_qf - d_fc) / 45.0  # (64q - 20f + c)/45 = q + (19(q-f) - (f-c))/45
    t = base + corr
    return t, ((t - base) - corr) + cb


def _repair(pos, vel, cp, cv, dsh, levels, comp):
    """Richardson repair of the coarse state (pos, vel; compensations cp, cv) from the shadows.
    Returns (new_pos, new_vel, new_cp, new_cv, estimated_error). Without compensation and with two
    levels this is exactly the original (4 x_fine - x_coarse) / 3 with its (4/3)|dx| estimate."""
    f = dsh[0]
    if not comp and levels < 3:
        est = (4.0 / 3.0) * position_error(pos, f[0])
        return (4.0 * f[0] - pos) / 3.0, (4.0 * f[1] - vel) / 3.0, cp, cv, est
    q = dsh[1] if levels >= 3 else f
    new_pos, new_cp = _repair_one(pos, cp, f[0], f[3], q[0], q[3], levels)
    new_vel, new_cv = _repair_one(vel, cv, f[1], f[4], q[1], q[4], levels)
    return new_pos, new_vel, new_cp, new_cv, position_error(pos, new_pos)


def run_adaptive(
    system: System,
    dt: float,
    total_time: float,
    sample_interval: float,
    safety_threshold: float,
    index_scale: IndexScale,
    raw_index_fn: Callable[[SafetyFeatures], np.ndarray],
    release_fraction: float = 0.8,
    reference: Trajectory | None = None,
    error_threshold: float | None = None,
    rewind: bool = False,
    checkpoint_count: int = 5,
    checkpoint_interval: int = 10,
    ias15_hold_steps: int = 0,
    rewind_back: int = 1,
    detect_false_positives: bool = False,
    false_positive_threshold: float | None = None,
    analyze_rollback: bool = False,
    oracle: Trajectory | None = None,
    rollback_error_threshold: float | None = None,
    rollback_clean_threshold: float = 1e-9,
    rollback_min_gain: float = 0.5,
    drift_budget: float = 0.0,
    drift_error_threshold: float | None = None,
    rewind_to_anchor: bool = False,
    resync_on_switch: bool = False,
    richardson_levels: int = 2,
    compensated_sums: bool = False,
) -> tuple[Trajectory, AdaptiveLog]:
    """
    Integrate `system` with the adaptive Leapfrog <-> IAS15 method.

    Args:
        system: Initial System. Not mutated.
        dt: Step length. Leapfrog steps use it directly; IAS15 is advanced
            to each multiple of dt (its own internal steps are adaptive and
            usually much smaller during close encounters).
        total_time: Total simulated duration.
        sample_interval: Time between recorded samples; must be an integer
            multiple of dt (same grid as the IAS15 / Leapfrog references).
        safety_threshold: Score in [0, 1] at or above which IAS15 is used.
        index_scale: How the raw index is converted to a 0-1 score.
        raw_index_fn: Callable mapping SafetyFeatures to a shape-(N,) raw
            index (higher == less safe). See core/safety_index.py.
        release_fraction: In (0, 1]. While in IAS15, return to Leapfrog only
            once the score falls below release_fraction * safety_threshold.
        reference: Optional IAS15 reference Trajectory on the same sample grid.
            If given (together with error_threshold), the SAME correction rule
            as core.leapfrog.run_leapfrog_with_correction is applied: at every
            sample, if the RMS position error vs the reference exceeds
            error_threshold, the state is snapped to the reference state. The
            returned Trajectory then holds the snapped states, and its
            pre_check_positions / pre_check_velocities hold the raw states, so
            errors can be counted exactly as in the calibration.
        error_threshold: RMS position-error threshold that triggers a correction.
        rewind: If True, on a Leapfrog -> IAS15 trigger restore an earlier checkpoint
            (see rewind_back) and continue with IAS15 from there instead of switching
            at the current state (see module docstring).
        checkpoint_count: How many checkpoints are kept in RAM (>= rewind_back + 1; the
            oldest is dropped when full). Only used with rewind.
        checkpoint_interval: Steps between checkpoints (>= 1). Only used with rewind.
        rewind_back: How many checkpoints before the latest one to restore (>= 0;
            1 = second-latest, 2 = third-latest, ...). If fewer checkpoints exist,
            the oldest is used. Only used with rewind.
        ias15_hold_steps: Steps IAS15 is kept after the score has fallen below the
            release threshold (>= 0).
        detect_false_positives: Track a shadow Leapfrog during every IAS15 stretch and
            classify each stretch as a false positive or not (see module docstring).
        false_positive_threshold: RMS position difference below which a stretch counts
            as a false positive. Required when detect_false_positives is True.
        analyze_rollback: Measure how many errors a deeper rollback could have prevented
            (see module docstring). Needs rewind=True, oracle and rollback_error_threshold.
        oracle: Exact IAS15 Trajectory on the same sample grid, used ONLY by the
            analysis (never to steer the integration).
        rollback_error_threshold: RMS position error vs the oracle above which a sample
            counts as an error in the analysis.
        rollback_clean_threshold: Largest RMS deviation still called 'adequate' for a
            checkpoint candidate (default 1e-9; the raw deviations are logged so this
            can be re-applied offline).
        rollback_min_gain: In (0, 1]. A rewind target counts as effective in the analysis
            if it removes at least this fraction of the un-rewound state's error
            (default 0.5).
        drift_budget: Fraction (>= 0) of drift_error_threshold at which the accumulated-
            drift estimate (dt/2 shadow Leapfrog, Richardson) triggers a resync. 0 = off.
        drift_error_threshold: RMS position error the drift budget is a fraction of
            (normally the correction threshold). Required when drift_budget > 0.
        rewind_to_anchor: With rewind, restore the last verified state (the anchor)
            instead of the checkpoint rewind_back places before the latest.
        resync_on_switch: Repair the state IAS15 takes over from with the Richardson
            extrapolation (dt/2 shadow), so Leapfrog error is not frozen into it.
        richardson_levels: 2 = dt/2 shadow, 4th-order repair (default); 3 = also a dt/4 shadow,
            6th-order repair (see module docstring).
        compensated_sums: Kahan-compensate the position / velocity sums (see module docstring).

    Returns:
        (Trajectory, AdaptiveLog), both sampled every `sample_interval`.

    Raises:
        ValueError: On invalid dt / total_time / sample_interval /
            safety_threshold / release_fraction.
    """
    if dt <= 0:
        raise ValueError(f"dt must be positive, got {dt}")
    if total_time <= 0:
        raise ValueError(f"total_time must be positive, got {total_time}")
    if not 0.0 <= safety_threshold <= 1.0:
        raise ValueError(f"safety_threshold must be in [0, 1], got {safety_threshold}")
    if not 0.0 < release_fraction <= 1.0:
        raise ValueError(f"release_fraction must be in (0, 1], got {release_fraction}")
    if (reference is None) != (error_threshold is None):
        raise ValueError("reference and error_threshold must be given together (or both omitted)")
    if error_threshold is not None and error_threshold <= 0:
        raise ValueError(f"error_threshold must be positive, got {error_threshold}")
    if rewind and rewind_back < 0:
        raise ValueError(f"rewind_back must be >= 0, got {rewind_back}")
    if rewind and checkpoint_count < rewind_back + 1:
        raise ValueError(
            f"checkpoint_count ({checkpoint_count}) must be >= rewind_back + 1 ({rewind_back + 1})"
        )
    if rewind and checkpoint_interval < 1:
        raise ValueError(f"checkpoint_interval must be >= 1, got {checkpoint_interval}")
    if ias15_hold_steps < 0:
        raise ValueError(f"ias15_hold_steps must be >= 0, got {ias15_hold_steps}")
    if detect_false_positives and (false_positive_threshold is None or false_positive_threshold <= 0):
        raise ValueError(
            "detect_false_positives needs a positive false_positive_threshold, "
            f"got {false_positive_threshold}"
        )
    if analyze_rollback:
        if not rewind:
            raise ValueError("analyze_rollback needs rewind=True")
        if oracle is None:
            raise ValueError("analyze_rollback needs an oracle trajectory")
        if rollback_error_threshold is None or rollback_error_threshold <= 0:
            raise ValueError(
                f"analyze_rollback needs a positive rollback_error_threshold, got {rollback_error_threshold}"
            )
        if rollback_clean_threshold < 0:
            raise ValueError(f"rollback_clean_threshold must be >= 0, got {rollback_clean_threshold}")
        if not 0.0 < rollback_min_gain <= 1.0:
            raise ValueError(f"rollback_min_gain must be in (0, 1], got {rollback_min_gain}")
    if drift_budget < 0:
        raise ValueError(f"drift_budget must be >= 0, got {drift_budget}")
    if drift_budget > 0 and (drift_error_threshold is None or drift_error_threshold <= 0):
        raise ValueError(
            f"drift_budget > 0 needs a positive drift_error_threshold, got {drift_error_threshold}"
        )
    if rewind_to_anchor and not rewind:
        raise ValueError("rewind_to_anchor needs rewind=True")
    if richardson_levels not in (2, 3):
        raise ValueError(f"richardson_levels must be 2 or 3, got {richardson_levels}")

    steps_per_sample_f = sample_interval / dt
    if abs(steps_per_sample_f - round(steps_per_sample_f)) > 1e-9 or steps_per_sample_f < 1:
        raise ValueError(
            f"sample_interval ({sample_interval}) must be a positive integer multiple of "
            f"dt ({dt}); got steps_per_sample={steps_per_sample_f}"
        )
    steps_per_sample = int(round(steps_per_sample_f))
    n_steps = int(round(total_time / dt))
    if reference is not None and reference.times.shape[0] < n_steps // steps_per_sample + 1:
        raise ValueError(
            f"reference has {reference.times.shape[0]} samples but the run needs "
            f"{n_steps // steps_per_sample + 1}"
        )
    if analyze_rollback and oracle.times.shape[0] < n_steps // steps_per_sample + 1:
        raise ValueError(
            f"oracle has {oracle.times.shape[0]} samples but the run needs "
            f"{n_steps // steps_per_sample + 1}"
        )

    working = system.copy()
    masses = working.masses()
    g = working.g
    softening = working.softening
    n = working.n

    positions = working.positions()
    velocities = working.velocities()
    acc = compute_accelerations(positions, masses, g=g, softening=softening)
    acc_prev: np.ndarray | None = None  # no history until the first step is done
    comp = bool(compensated_sums)
    cx = np.zeros_like(positions)  # Kahan compensation of the position / velocity sums
    cv = np.zeros_like(velocities)

    configure = getattr(raw_index_fn, "configure", None)
    if callable(configure):  # stateful index (core/situations.py): hand it the run constants + t=0 state
        configure(
            masses=masses,
            g=g,
            softening=softening,
            dt=dt,
            steps_per_sample=steps_per_sample,
            n_steps=n_steps,
            positions=positions,
            velocities=velocities,
        )

    mode = "leapfrog"
    sim: rebound.Simulation | None = None
    score = 0.0  # score of the CURRENT state; unknown at t=0 (jerk undefined)
    raw_now = float("nan")

    times_out = [0.0]
    positions_out = [positions.copy()]
    velocities_out = [velocities.copy()]
    active_out = ["leapfrog"]
    frac_out = [0.0]
    raw_out = [float("nan")]
    score_out = [float("nan")]
    nsw_out = [0]

    correcting = reference is not None
    n_corrections = 0
    pre_positions_out = [positions.copy()]
    pre_velocities_out = [velocities.copy()]

    events: list[SwitchEvent] = []
    n_switches = 0
    n_ias15_steps = 0
    ias15_steps_this_interval = 0

    # --- rewind machinery (see module docstring) ---
    release_threshold = release_fraction * safety_threshold
    hold_remaining = 0  # IAS15 steps still to take after the score fell below release_threshold
    force_ias15_until = 0  # steps <= this are taken by IAS15 unconditionally (post-rewind replay)
    rewind_events: list[RewindEvent] = []
    n_rewound_steps = 0
    # --- false-positive detection ---
    detect_fp = bool(detect_false_positives)
    fp_threshold = float(false_positive_threshold) if detect_fp else float("nan")
    stretches: list[IAS15Stretch] = []
    active: _ActiveStretch | None = None
    # --- rollback-depth analysis ---
    analyze = bool(analyze_rollback)
    rollback_errors: list[RollbackError] = []
    taint = [False, False, False]  # (improvable, drift_dominated, adequate) rewinds since last clean point
    # --- drift budget (dt/2 shadow Leapfrog + Richardson resync) ---
    drift_on = drift_budget > 0 or resync_on_switch  # the dt/2 shadow runs
    drift_limit = drift_budget * drift_error_threshold if drift_budget > 0 else float("inf")
    resync_events: list[ResyncEvent] = []
    dshadow = _new_shadow(positions, velocities, acc, cx, cv, richardson_levels) if drift_on else None

    def oracle_pos(t_step: int) -> np.ndarray:
        """Exact IAS15 positions at step `t_step` (oracle sample + a short IAS15 advance)."""
        s = t_step // steps_per_sample
        return _ias15_replay(
            oracle.positions[s], oracle.velocities[s], masses, g, softening,
            s * steps_per_sample, dt, t_step - s * steps_per_sample,
        )

    def analyze_rewind(t_step: int) -> RollbackAnalysis:
        """Replay IAS15 from every queued checkpoint to `t_step` and score it against the oracle."""
        s = t_step // steps_per_sample
        o_pos = _ias15_replay(
            oracle.positions[s], oracle.velocities[s], masses, g, softening,
            s * steps_per_sample, dt, t_step - s * steps_per_sample,
        )
        dev_leap = float(position_error(positions, o_pos))
        limit = max(rollback_clean_threshold, (1.0 - rollback_min_gain) * dev_leap)  # effective if <= limit
        dev_anchor: float | None = None
        anchor_step: int | None = None
        if anchor is not None and (rewind_to_anchor or t_step - anchor.step <= _ANCHOR_REPLAY_CAP):
            p_a = _ias15_replay(
                anchor.positions, anchor.velocities, masses, g, softening, anchor.step, dt, t_step - anchor.step
            )
            dev_anchor = float(position_error(p_a, o_pos))
            anchor_step = anchor.step
        if rewind_to_anchor:  # the anchor IS the restore point: no queue candidates needed
            return RollbackAnalysis(
                dev_leapfrog=dev_leap,
                dev_by_depth=[],
                steps_by_depth=[],
                chosen_depth=-1,
                category="adequate" if dev_anchor <= limit else "drift_dominated",
                best_depth=-1,
                min_adequate_depth=-1,
                dev_anchor=dev_anchor,
                anchor_step=anchor_step,
            )
        n_cand = len(checkpoints)
        devs: list[float] = []
        cp_steps: list[int] = []
        for d in range(n_cand):
            cp = checkpoints[n_cand - 1 - d]
            p = _ias15_replay(
                cp.positions, cp.velocities, masses, g, softening, cp.step, dt, t_step - cp.step
            )
            devs.append(float(position_error(p, o_pos)))
            cp_steps.append(cp.step)
        chosen_depth = n_cand - 1 - max(n_cand - 1 - rewind_back, 0)
        adequate = [x <= limit for x in devs]
        if adequate[chosen_depth]:
            category, min_adequate = "adequate", chosen_depth
        else:
            deeper = [d for d in range(chosen_depth + 1, n_cand) if adequate[d]]
            category = "improvable" if deeper else "drift_dominated"
            min_adequate = deeper[0] if deeper else -1
        return RollbackAnalysis(
            dev_leapfrog=dev_leap,
            dev_by_depth=devs,
            steps_by_depth=cp_steps,
            chosen_depth=chosen_depth,
            category=category,
            best_depth=int(np.argmin(devs)),
            min_adequate_depth=min_adequate,
            dev_anchor=dev_anchor,
            anchor_step=anchor_step,
        )

    def close_stretch(a: _ActiveStretch, end_step: int, complete: bool) -> IAS15Stretch:
        return IAS15Stretch(
            start_step=a.start_step,
            start_time=a.start_time,
            end_step=end_step,
            n_steps=a.n_steps,
            trigger_score=a.trigger_score,
            peak_score=a.peak_score,
            max_deviation=a.max_dev,
            false_positive=a.max_dev < fp_threshold,
            rewound=a.rewound,
            complete=complete,
        )

    checkpoints: deque = deque(maxlen=max(checkpoint_count, 1))
    index_snapshot = getattr(raw_index_fn, "snapshot_state", None)
    index_restore = getattr(raw_index_fn, "restore_state", None)
    if rewind and callable(configure) and not (callable(index_snapshot) and callable(index_restore)):
        raise ValueError(
            "rewind=True needs a stateless raw index or one that implements "
            "snapshot_state() / restore_state() (SituationIndex does)."
        )
    # every per-sample output list has the same length; rewinding truncates them together
    out_lists = (
        times_out, positions_out, velocities_out, active_out, frac_out,
        raw_out, score_out, nsw_out, pre_positions_out, pre_velocities_out,
    )

    def make_checkpoint(step_now: int) -> _Checkpoint:
        """Snapshot the current state (reads the enclosing locals as they are right now)."""
        return (
            _Checkpoint(
                step=step_now,
                positions=positions.copy(),
                velocities=velocities.copy(),
                acc=acc.copy(),
                acc_prev=None if acc_prev is None else acc_prev.copy(),
                score=score,
                raw_now=raw_now,
                n_switches=n_switches,
                n_events=len(events),
                n_ias15_steps=n_ias15_steps,
                ias15_steps_this_interval=ias15_steps_this_interval,
                n_corrections=n_corrections,
                n_samples=len(times_out),
                index_state=index_snapshot() if callable(index_snapshot) else None,
                stretch=None if active is None else active.copy(),
                n_stretches=len(stretches),
                n_rollback_errors=len(rollback_errors),
                taint=tuple(taint),
                n_resyncs=len(resync_events),
                drift=dshadow,
                cx=cx.copy(),
                cv=cv.copy(),
            )
        )

    def save_checkpoint(step_now: int) -> None:
        checkpoints.append(make_checkpoint(step_now))

    anchor: _Checkpoint | None = None  # last verified state (start / resync / snap / anchored release)
    anchor_pending = False  # set mid-step; the anchor is captured at the end of the iteration
    anchored_stretch = False  # the IAS15 stretch in progress started from the anchor

    if rewind:
        save_checkpoint(0)
        anchor = make_checkpoint(0)

    step = 1
    while step <= n_steps:
        t_start = (step - 1) * dt
        t_end = step * dt

        # 1. Which integrator takes this step?
        if step <= force_ias15_until:
            want_ias15 = True  # replaying after a rewind: IAS15 up to the detection step
        elif acc_prev is None:
            want_ias15 = False  # first step: no jerk history to judge from
        elif mode == "leapfrog":
            want_ias15 = score >= safety_threshold
            if want_ias15 and rewind:
                if rewind_to_anchor:
                    target = anchor  # far rollback: the last verified state
                    chosen_depth = -1
                else:
                    # Detected (late): go back `rewind_back` checkpoints before the latest.
                    target = checkpoints[max(len(checkpoints) - 1 - rewind_back, 0)]
                    chosen_depth = len(checkpoints) - 1 - max(len(checkpoints) - 1 - rewind_back, 0)
                detect_score = score
                analysis = analyze_rewind(step - 1) if analyze else None  # needs the pre-restore state
                for lst in out_lists:
                    del lst[target.n_samples:]
                del events[target.n_events:]
                if rewind_to_anchor:
                    checkpoints.clear()  # everything newer than the anchor is a discarded timeline
                    checkpoints.append(target)
                else:
                    while checkpoints[-1] is not target:
                        checkpoints.pop()  # newer checkpoints belong to the discarded timeline
                n_rewound_steps += (step - 1) - target.step
                rewind_events.append(
                    RewindEvent(
                        step, target.step, t_start, target.step * dt, detect_score,
                        depth=chosen_depth, analysis=analysis,
                    )
                )
                positions = target.positions.copy()
                velocities = target.velocities.copy()
                acc = target.acc.copy()
                cx, cv = target.cx.copy(), target.cv.copy()
                acc_prev = None if target.acc_prev is None else target.acc_prev.copy()
                score, raw_now = target.score, target.raw_now
                n_switches = target.n_switches
                n_ias15_steps = target.n_ias15_steps
                ias15_steps_this_interval = target.ias15_steps_this_interval
                n_corrections = target.n_corrections
                if analyze:
                    del rollback_errors[target.n_rollback_errors:]
                    taint = list(target.taint)
                    taint[{"improvable": 0, "drift_dominated": 1, "adequate": 2}[analysis.category]] = True
                del resync_events[target.n_resyncs:]
                dshadow = None  # replay is IAS15; the dt/2 shadow restarts at release
                anchored_stretch = rewind_to_anchor
                if detect_fp:
                    del stretches[target.n_stretches:]
                    if target.stretch is not None:
                        active = target.stretch.copy()  # stretch was already running at the checkpoint
                    else:  # new stretch; its shadow restarts from the checkpoint = the discarded timeline
                        active = _ActiveStretch(
                            start_step=target.step + 1,
                            start_time=target.step * dt,
                            trigger_score=detect_score,
                            rewound=True,
                            sh_pos=positions.copy(),
                            sh_vel=velocities.copy(),
                            sh_acc=acc.copy(),
                            peak_score=detect_score,
                        )
                if callable(index_restore):
                    index_restore(target.index_state)
                if resync_on_switch and target.drift is not None:
                    # Repair the restore state before IAS15 freezes its Leapfrog error in it:
                    # Richardson extrapolation with the dt/2 shadow saved in the checkpoint.
                    new_pos, new_vel, cx, cv, est_sw = _repair(
                        positions, velocities, cx, cv, target.drift, richardson_levels, comp
                    )
                    dev_b = dev_a = None
                    if analyze:
                        o_pos = oracle_pos(target.step)
                        dev_b = float(position_error(positions, o_pos))
                        dev_a = float(position_error(new_pos, o_pos))
                    positions, velocities = new_pos, new_vel
                    acc = compute_accelerations(positions, masses, g=g, softening=softening)
                    resync_events.append(
                        ResyncEvent(target.step, target.step * dt, float(est_sw), dev_b, dev_a, "switch")
                    )
                    anchor = make_checkpoint(target.step)  # the repaired state is the new verified anchor
                sim = _make_ias15_sim(positions, velocities, masses, g, softening, target.step * dt)
                mode = "ias15"
                n_switches += 1
                events.append(SwitchEvent(target.step + 1, target.step * dt, "ias15", detect_score))
                hold_remaining = ias15_hold_steps
                force_ias15_until = step  # the step that was about to be taken is replayed too
                step = target.step + 1
                continue
        else:
            if score >= release_threshold:
                hold_remaining = ias15_hold_steps
                want_ias15 = True
            elif hold_remaining > 0:
                hold_remaining -= 1
                want_ias15 = True
            else:
                want_ias15 = False

        if want_ias15 and mode == "leapfrog":
            if resync_on_switch and dshadow is not None:  # plain switch (no rewinding): repair the state
                new_pos, new_vel, cx, cv, est_sw = _repair(
                    positions, velocities, cx, cv, dshadow, richardson_levels, comp
                )
                dev_b = dev_a = None
                if analyze:
                    o_pos = oracle_pos(step - 1)
                    dev_b = float(position_error(positions, o_pos))
                    dev_a = float(position_error(new_pos, o_pos))
                positions, velocities = new_pos, new_vel
                acc = compute_accelerations(positions, masses, g=g, softening=softening)
                resync_events.append(ResyncEvent(step - 1, t_start, float(est_sw), dev_b, dev_a, "switch"))
            sim = _make_ias15_sim(positions, velocities, masses, g, softening, t_start)
            mode = "ias15"
            hold_remaining = ias15_hold_steps
            n_switches += 1
            events.append(SwitchEvent(step, t_start, "ias15", score))
            dshadow = None
            anchored_stretch = False
            if detect_fp:
                active = _ActiveStretch(
                    start_step=step,
                    start_time=t_start,
                    trigger_score=score,
                    rewound=False,
                    sh_pos=positions.copy(),
                    sh_vel=velocities.copy(),
                    sh_acc=acc.copy(),
                    peak_score=score,
                )
        elif not want_ias15 and mode == "ias15":
            # positions / velocities / acc already describe the current state
            # (they are refreshed after every IAS15 step below).
            if active is not None:
                stretches.append(close_stretch(active, step - 1, True))
                active = None
            if rewind and anchored_stretch:
                anchor = make_checkpoint(step - 1)  # IAS15 from a verified state: still clean
            anchored_stretch = False
            if drift_on:
                dshadow = _new_shadow(positions, velocities, acc, cx, cv, richardson_levels)
            sim = None
            mode = "leapfrog"
            n_switches += 1
            events.append(SwitchEvent(step, t_start, "leapfrog", score))

        # 2. Advance one dt.
        if mode == "leapfrog":
            positions, velocities, new_acc, cx, cv = _vv_step(
                (positions, velocities, acc, cx, cv), masses, g, softening, dt, comp
            )
            if dshadow is not None:
                dshadow = _advance_shadow(dshadow, masses, g, softening, dt, richardson_levels, comp)
        else:
            sim.integrate(t_end, exact_finish_time=1)
            positions, velocities = _read_state(sim, n)
            cx, cv = np.zeros_like(positions), np.zeros_like(velocities)  # REBOUND state is exact as read
            new_acc = compute_accelerations(positions, masses, g=g, softening=softening)
            n_ias15_steps += 1
            ias15_steps_this_interval += 1

        acc_prev, acc = acc, new_acc

        # 3. Safety features / score for the new state.
        features = compute_safety_features(positions, velocities, acc, acc_prev, dt, masses, step=step)
        raw_vec = np.broadcast_to(np.asarray(raw_index_fn(features), dtype=np.float64), (n,))
        score = system_safety_score(raw_vec, index_scale)
        finite = raw_vec[np.isfinite(raw_vec)]
        raw_now = float(finite.max()) if finite.size else float("nan")

        if drift_budget > 0 and dshadow is not None and mode == "leapfrog":
            # Richardson: velocity Verlet is 2nd order, so err(dt) ~ (4/3) * |x(dt) - x(dt/2)|.
            new_pos, new_vel, new_cx, new_cv, est = _repair(
                positions, velocities, cx, cv, dshadow, richardson_levels, comp
            )
            if est >= drift_limit:
                cx, cv = new_cx, new_cv
                dev_b = dev_a = None
                if analyze:
                    o_pos = oracle_pos(step)
                    dev_b = float(position_error(positions, o_pos))
                    dev_a = float(position_error(new_pos, o_pos))
                positions, velocities = new_pos, new_vel
                acc = compute_accelerations(positions, masses, g=g, softening=softening)
                dshadow = _new_shadow(positions, velocities, acc, cx, cv, richardson_levels)
                resync_events.append(ResyncEvent(step, t_end, float(est), dev_b, dev_a, "budget"))
                anchor_pending = True
                if analyze:
                    taint = [False, False, False]  # repaired: clean again

        if active is not None:
            # Shadow Leapfrog: what pure Leapfrog would have done from the stretch's start state.
            sp = active.sh_pos + active.sh_vel * dt + 0.5 * active.sh_acc * dt * dt
            sa = compute_accelerations(sp, masses, g=g, softening=softening)
            active.sh_vel = active.sh_vel + 0.5 * (active.sh_acc + sa) * dt
            active.sh_pos, active.sh_acc = sp, sa
            dev = position_error(positions, sp)
            if not np.isfinite(dev):
                dev = float("inf")  # shadow blew up: Leapfrog certainly was not fine
            active.max_dev = max(active.max_dev, dev)
            active.peak_score = max(active.peak_score, score)
            active.n_steps += 1

        if step % steps_per_sample == 0:
            # Raw (pre-correction) state: what errors are counted against.
            pre_positions_out.append(positions.copy())
            pre_velocities_out.append(velocities.copy())

            if analyze:
                err_now = position_error(positions, oracle.positions[len(times_out)])
                if err_now > rollback_error_threshold:
                    if taint[0]:
                        category = "improvable"
                    elif taint[1]:
                        category = "accumulated_drift"
                    elif taint[2]:
                        category = "after_adequate_rewinds"
                    else:
                        category = "undetected"
                    rollback_errors.append(
                        RollbackError(step=step, time=t_end, error=float(err_now), category=category)
                    )

            if correcting:
                k = len(times_out)  # index of the sample being recorded
                if position_error(positions, reference.positions[k]) > error_threshold:
                    n_corrections += 1
                    if analyze:
                        taint = [False, False, False]  # snapped to the reference: clean again
                    anchor_pending = True
                    positions = reference.positions[k].copy()
                    velocities = reference.velocities[k].copy()
                    acc = compute_accelerations(positions, masses, g=g, softening=softening)
                    cx, cv = np.zeros_like(positions), np.zeros_like(velocities)
                    if dshadow is not None:
                        dshadow = _new_shadow(positions, velocities, acc, cx, cv, richardson_levels)
                    if mode == "ias15":
                        # the live REBOUND sim still holds the erroneous state
                        sim = _make_ias15_sim(positions, velocities, masses, g, softening, t_end)

            times_out.append(t_end)
            positions_out.append(positions.copy())
            velocities_out.append(velocities.copy())
            active_out.append(mode)
            frac_out.append(ias15_steps_this_interval / steps_per_sample)
            raw_out.append(raw_now)
            score_out.append(score)
            nsw_out.append(n_switches)
            ias15_steps_this_interval = 0

        if rewind and anchor_pending:
            anchor = make_checkpoint(step)
            anchor_pending = False

        if rewind and step % checkpoint_interval == 0:
            save_checkpoint(step)

        step += 1

    if active is not None:  # the run ended inside an IAS15 stretch
        stretches.append(close_stretch(active, n_steps, False))
        active = None

    trajectory = Trajectory(
        times=np.array(times_out, dtype=np.float64),
        positions=np.array(positions_out, dtype=np.float64),
        velocities=np.array(velocities_out, dtype=np.float64),
        masses=masses,
        pre_check_positions=np.array(pre_positions_out, dtype=np.float64) if correcting else None,
        pre_check_velocities=np.array(pre_velocities_out, dtype=np.float64) if correcting else None,
    )
    log = AdaptiveLog(
        active_integrator=np.array(active_out, dtype=object),
        ias15_step_fraction=np.array(frac_out, dtype=np.float64),
        raw_index=np.array(raw_out, dtype=np.float64),
        safety_score=np.array(score_out, dtype=np.float64),
        n_switches=np.array(nsw_out, dtype=np.int64),
        switch_events=events,
        n_steps=n_steps,
        n_ias15_steps=n_ias15_steps,
        n_corrections=n_corrections,
        rewind_events=rewind_events,
        n_rewinds=len(rewind_events),
        n_rewound_steps=n_rewound_steps,
        stretches=stretches,
        fp_detection=detect_fp,
        fp_threshold=fp_threshold if detect_fp else None,
        rollback_errors=rollback_errors,
        rollback_analysis=analyze,
        resync_events=resync_events,
        n_resyncs=len(resync_events),
        drift_budget=float(drift_budget),
        resync_on_switch=bool(resync_on_switch),
    )
    return trajectory, log
